server:
  port: 8080


#logging:
#   file: /tmp/mylogs/my.log
#   file.max-size: 10MB
#   pattern:
#      console: "%d{yyyy-MM-dd HH:mm:ss} -%-4r [%t] %-5level %logger{36} - %msg%n"
#   level:
#     root: debug
#     org.springframework.web: debug
#     org.hibernate: debug
#     com.wy: debug

app:
  name: appName
  type: dev

app2:
  name: appName2
  type: dev2